"""Reusable SVG labeling module for web/API integrations.

The module annotates each visible SVG path with stitch labels generated by the
same OpenCV rule pipeline used by scripts/inference/opencv_stitch_classifier.py.
"""

from __future__ import annotations

import copy
import os
import tempfile
import xml.etree.ElementTree as ET
from dataclasses import dataclass
from io import BytesIO
from pathlib import Path
from typing import Dict, Iterable, List, Optional, Tuple, Union

import cv2
import numpy as np
from PIL import Image

from scripts.inference import opencv_stitch_classifier as classifier

INKSCAPE_URI = "http://www.inkscape.org/namespaces/inkscape"
INKSCAPE_LABEL_ATTR = f"{{{INKSCAPE_URI}}}label"

ET.register_namespace("", "http://www.w3.org/2000/svg")
ET.register_namespace("inkscape", INKSCAPE_URI)
ET.register_namespace("sodipodi", "http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd")

PathLike = Union[str, os.PathLike]


@dataclass(frozen=True)
class LabelingConfig:
    """Configuration for SVG stitch labeling."""

    fallback_physical_width_mm: float = classifier.DEFAULT_PHYSICAL_WIDTH_MM
    canvas_w: int = classifier.DEFAULT_SVG_CANVAS_W
    canvas_h: int = classifier.DEFAULT_SVG_CANVAS_H
    classify_scale: float = classifier.SVG_CLASSIFY_SCALE
    min_region_pixels: int = 5
    enable_context_refinement: bool = True
    use_existing_svg_labels: bool = False
    label_attr: str = "inkscape_label"
    write_data_attrs: bool = True
    write_css_class: bool = False
    default_unclassified_label: Optional[str] = None
    verbose: bool = False


@dataclass(frozen=True)
class LabelingResult:
    """Output from a labeling request."""

    svg_text: str
    labels: Dict[str, str]
    counts: Dict[str, int]
    source_name: Optional[str] = None
    output_path: Optional[str] = None

    @property
    def svg_bytes(self) -> bytes:
        return self.svg_text.encode("utf-8")


def label_svg_file(
    input_svg: PathLike,
    output_svg: Optional[PathLike] = None,
    config: Optional[LabelingConfig] = None,
) -> LabelingResult:
    """Label one SVG file and optionally write the labeled SVG to disk."""

    cfg = config or LabelingConfig()
    input_path = Path(input_svg)
    tree = ET.parse(input_path)
    root = tree.getroot()

    result = _label_svg_root(
        root=root,
        source_svg_path=str(input_path),
        source_name=input_path.name,
        config=cfg,
    )

    if output_svg is not None:
        output_path = Path(output_svg)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(result.svg_text, encoding="utf-8")
        result = LabelingResult(
            svg_text=result.svg_text,
            labels=result.labels,
            counts=result.counts,
            source_name=result.source_name,
            output_path=str(output_path),
        )

    return result


def label_svg_bytes(
    svg_bytes: bytes,
    source_name: Optional[str] = None,
    config: Optional[LabelingConfig] = None,
) -> LabelingResult:
    """Label an uploaded SVG payload and return the labeled SVG text."""

    cfg = config or LabelingConfig()
    root = ET.fromstring(svg_bytes)

    # CairoSVG often needs a URL/base path. A temporary SVG keeps the classifier
    # path-compatible while still exposing a bytes-friendly web API.
    suffix = Path(source_name or "upload.svg").suffix or ".svg"
    with tempfile.NamedTemporaryFile(suffix=suffix, delete=True) as tmp:
        tmp.write(svg_bytes)
        tmp.flush()
        return _label_svg_root(
            root=root,
            source_svg_path=tmp.name,
            source_name=source_name,
            config=cfg,
        )


def label_svg_files(
    input_svgs: Iterable[PathLike],
    output_dir: Optional[PathLike] = None,
    config: Optional[LabelingConfig] = None,
    suffix: str = "_labeled",
) -> List[LabelingResult]:
    """Label multiple SVG files.

    When output_dir is provided, each result is written as
    ``<original_stem><suffix>.svg``.
    """

    cfg = config or LabelingConfig()
    output_base = Path(output_dir) if output_dir is not None else None
    results: List[LabelingResult] = []

    for input_svg in input_svgs:
        input_path = Path(input_svg)
        output_svg = None
        if output_base is not None:
            output_svg = output_base / f"{input_path.stem}{suffix}.svg"
        results.append(label_svg_file(input_path, output_svg=output_svg, config=cfg))

    return results


def _label_svg_root(
    root: ET.Element,
    source_svg_path: str,
    source_name: Optional[str],
    config: LabelingConfig,
) -> LabelingResult:
    path_elems, path_labels = _classify_path_labels(root, source_svg_path, config)
    labels = _apply_labels_to_svg(root, path_elems, path_labels, config)
    counts = {
        "fill": sum(1 for label in labels.values() if label == "fill"),
        "satin": sum(1 for label in labels.values() if label == "satin"),
        "unclassified": len(path_elems) - len(labels),
        "paths": len(path_elems),
    }
    svg_text = _serialize_svg(root)
    return LabelingResult(
        svg_text=svg_text,
        labels=labels,
        counts=counts,
        source_name=source_name,
    )


def _classify_path_labels(
    root: ET.Element,
    source_svg_path: str,
    config: LabelingConfig,
) -> Tuple[List[ET.Element], List[Optional[str]]]:
    if classifier.cairosvg is None:
        raise ImportError("cairosvg is required to label SVG files.")

    classify_scale = min(max(config.classify_scale, 1e-3), 1.0)
    parent_map = {child: parent for parent in root.iter() for child in parent}
    path_elems = [
        elem
        for elem in root.iter()
        if classifier._tag(elem) == "path"
        and not classifier._is_in_defs_or_clip(elem, parent_map)
    ]

    if not path_elems:
        return [], []

    render_root = copy.deepcopy(root)
    render_parent_map = {child: parent for parent in render_root.iter() for child in parent}
    render_path_elems = [
        elem
        for elem in render_root.iter()
        if classifier._tag(elem) == "path"
        and not classifier._is_in_defs_or_clip(elem, render_parent_map)
    ]

    full_png = classifier.cairosvg.svg2png(
        url=source_svg_path,
        output_width=config.canvas_w,
        output_height=config.canvas_h,
        background_color=None,
        unsafe=True,
    )
    full_rgba = np.array(Image.open(BytesIO(full_png)).convert("RGBA"))
    total_fg = full_rgba[:, :, 3] >= 128

    path_labels: List[Optional[str]] = [None] * len(render_path_elems)
    if not total_fg.any():
        return path_elems, path_labels

    canvas_physical_mm = classifier.parse_svg_physical_width(
        render_root,
        config.fallback_physical_width_mm,
    )
    ys, xs = np.where(total_fg)
    crop_w = xs.max() - xs.min() + 1
    logo_real_w_mm = canvas_physical_mm * (crop_w / config.canvas_w)
    dynamic_threshold_mm = logo_real_w_mm / 6.0

    if config.verbose:
        print(
            f">> [SVG Labeler] Logo Real Width = {logo_real_w_mm:.2f}mm | "
            f"Threshold = {dynamic_threshold_mm:.2f}mm"
        )

    small_w = max(1, int(round(config.canvas_w * classify_scale)))
    small_h = max(1, int(round(config.canvas_h * classify_scale)))
    small_canvas_shape = (small_h, small_w)
    pixel_to_mm_small = canvas_physical_mm / max(float(small_w), 1.0)
    small_total_fg = cv2.resize(
        total_fg.astype(np.uint8),
        (small_w, small_h),
        interpolation=cv2.INTER_NEAREST,
    )
    small_total_fg_area_px = float(np.count_nonzero(small_total_fg))

    label_mask_small = np.zeros((small_h, small_w), dtype=np.uint8)
    global_records: List[classifier._GlobalShapeRecord] = []
    shape_path_idx: List[int] = []
    global_id_counter = 0

    saved_displays = {elem: elem.attrib.get("display") for elem in render_path_elems}
    for elem in render_path_elems:
        elem.set("display", "none")

    try:
        for idx, path_elem in enumerate(render_path_elems):
            if config.use_existing_svg_labels:
                pre_label = classifier.get_declared_label(path_elem)
                if pre_label:
                    path_labels[idx] = pre_label
                    continue

            path_mask01 = classifier._render_single_path_mask_fast(
                path_elem,
                render_root,
                small_w,
                small_h,
            )
            n_pixels = int(path_mask01.sum())
            if n_pixels < config.min_region_pixels:
                continue

            binary_mask_255 = (path_mask01 * 255).astype(np.uint8)
            shapes, sub_label_mask = classifier.classify_binary_mask(
                binary_mask_255,
                physical_width_mm=canvas_physical_mm,
                threshold_mm=dynamic_threshold_mm,
                total_fg_area_px=small_total_fg_area_px,
                verbose=config.verbose,
            )
            label_mask_small[sub_label_mask > 0] = sub_label_mask[sub_label_mask > 0]

            for shape in shapes:
                if shape.label not in ("satin", "fill"):
                    continue
                shape.global_id = global_id_counter
                global_id_counter += 1
                shape_mask_small = classifier.shape_to_mask(shape, small_canvas_shape)
                area_px = int(np.count_nonzero(shape_mask_small))
                global_records.append(
                    classifier._GlobalShapeRecord(shape, shape_mask_small, area_px)
                )
                shape_path_idx.append(idx)
    finally:
        for elem, display_value in saved_displays.items():
            if display_value is None:
                elem.attrib.pop("display", None)
            else:
                elem.set("display", display_value)

    if config.enable_context_refinement and global_records:
        classifier.refine_labels_by_context(
            global_records,
            label_mask_small,
            small_canvas_shape,
            pixel_to_mm=pixel_to_mm_small,
            verbose=config.verbose,
        )

    path_satin_area = [0] * len(render_path_elems)
    path_fill_area = [0] * len(render_path_elems)
    for record, path_idx in zip(global_records, shape_path_idx):
        if record.shape.label == "satin":
            path_satin_area[path_idx] += record.area_px
        elif record.shape.label == "fill":
            path_fill_area[path_idx] += record.area_px

    for idx in range(len(render_path_elems)):
        if path_labels[idx] is not None:
            continue
        satin_area = path_satin_area[idx]
        fill_area = path_fill_area[idx]
        if satin_area > 0 or fill_area > 0:
            path_labels[idx] = "satin" if satin_area >= fill_area else "fill"

    return path_elems, path_labels


def _apply_labels_to_svg(
    root: ET.Element,
    path_elems: List[ET.Element],
    path_labels: List[Optional[str]],
    config: LabelingConfig,
) -> Dict[str, str]:
    labels: Dict[str, str] = {}

    for idx, (path_elem, label) in enumerate(zip(path_elems, path_labels)):
        if label is None:
            label = config.default_unclassified_label
        if label not in ("fill", "satin"):
            continue

        path_id = _ensure_path_id(path_elem, idx)
        labels[path_id] = label

        if config.label_attr == "inkscape_label":
            path_elem.set(INKSCAPE_LABEL_ATTR, label)
        elif config.label_attr:
            path_elem.set(config.label_attr, label)

        if config.write_data_attrs:
            path_elem.set("data-stitch", label)
            path_elem.set("data-label", label)

        if config.write_css_class:
            _append_css_class(path_elem, f"stitch-{label}")

    return labels


def _ensure_path_id(path_elem: ET.Element, index: int) -> str:
    path_id = path_elem.get("id")
    if path_id:
        return path_id
    path_id = f"stitch_path_{index + 1}"
    path_elem.set("id", path_id)
    return path_id


def _append_css_class(elem: ET.Element, class_name: str) -> None:
    existing = elem.get("class", "")
    classes = [item for item in existing.split() if item]
    if class_name not in classes:
        classes.append(class_name)
    elem.set("class", " ".join(classes))


def _serialize_svg(root: ET.Element) -> str:
    return ET.tostring(root, encoding="unicode")
